name: Update Gist with Current Primes

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # or whichever version you're using
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run script
      run: npm start
      
    - name: Update Gist
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        content=$(cat currentPrimes.md)
        content="${content//$'\n'/\\n}"
        content="${content//$'\r'/}"
        content="${content//\"/\\\"}"
        json_payload=$(jq -n --arg content "$content" '{files: {"current_primes.md": {content: $content}}}')
        curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/gists/$GIST_ID \
          -d "$json_payload"